[tool.poetry.dependencies]
setuptools = { version = "<45.0.0", python = "<3" }
boto3 = "~=1.12"
dataclasses = { version = ">=0.6", python = "<3.7" }
deprecated = "~=1.2"
frozendict = "~=1.2"
google-api-python-client = "~=1.8"
oauth2client = "~=4.1"
pbkdf2 = "~=1.3"
python-json-logger = "~=2.0"
python-dateutil = "~=2.8"
requests = "~=2.9"
semver = "~=2.9"
simplejson = "~=3.17"
six = "~=1.15"
marshmallow = "~=2.21"
foo = "<1,>=0.6"
baz = "*"

[tool.poetry.dev-dependencies]
bunch = "~=1.0"
pytest = "~=5.4"
pytest-cov = "~=2.8"
pytz = { version = "~=2019.1", python = "<3" }
lib-test = "~=2.1"
mock = "~=4.0"
coverage = "~=5.1"
requests-mock = "~=1.8.0"
moto = "*"
httpretty = "*"
backports.cached-property = "*"
pydash = "*"
